services:
  wardrobe.api:
    image: wardrobe.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 5000:80
    build:
      context: .
      dockerfile: Wardrobe.API/Dockerfile