# fly.toml app configuration file generated for wardrobe-api on 2023-08-22T23:01:18-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wardrobe-api"
primary_region = "gru"

[build]
  dockerfile = "./Wardrobe.API/Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
